### ISSUE TITLE
Installation issue gcc-go-8.2.1+20181127-1

### ISSUE THREAD

**Issue by ashwinvis** [kis3/kis3#5]
Traceback:
```sh
% go get -u github.com/kis3/kis3
# golang.org/x/sys/unix
go/src/golang.org/x/sys/unix/syscall_linux_gccgo_arm.go:14:1: error: redefinition of ‘seek’
 func seek(fd int, offset int64, whence int) (int64, syscall.Errno) {
 ^
go/src/golang.org/x/sys/unix/syscall_linux_arm.go:54:1: note: previous definition of ‘seek’ was here
 func seek(fd int, offset int64, whence int) (newoffset int64, err syscall.Errno)
 ^
```

**Comment by jlelse** [comment]
Which version of Go are you using?

**Comment by jlelse** [comment]
Are you trying to cross compile?

**Comment by ashwinvis** [comment]
gcc-go package provided by ArchLinux ARM: https://archlinuxarm.org/packages/armv7h/gcc-go/files/PKGBUILD

I am compiling on raspberry pi itself (arm7)

**Comment by jlelse** [comment]
I have no idea where that error can come from. The Docker build on arm / arm64 is working fine. Maybe that's you Go version or some arch specific thing? Maybe try to uninstall gcc-go and just install normal go?

**Comment by ashwinvis** [comment]
I will try either a system upgrade and/or normal go and get back to you.

**Comment by ashwinvis** [comment]
After a full upgrade and replacing gcc-go with go-pie it installs.

**Comment by jlelse** [comment]
Great!
